load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

############################################################
## rules_ls_lint ###########################################
############################################################

#local_repository(
#    name = "com_github_ls_lint_rules_ls_lint",
#    path = "..",
#)

http_archive(
    name = "com_github_ls_lint_rules_ls_lint",
    sha256 = "a9cc71df0373f75388b14a0e49ff694cd617b38efe129ede25d9dc8f5f1d0d8a",
    urls = [
        "https://github.com/ls-lint/rules_ls_lint/archive/refs/tags/v0.1.0.tar.gz",
    ],
)

load("@com_github_ls_lint_rules_ls_lint//:repositories.bzl", "rules_ls_lint_dependencies")

rules_ls_lint_dependencies(version = "1.11.2")

############################################################
## rules_go: setup #########################################
############################################################

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.20.2")

############################################################
## gazelle: setup ##########################################
############################################################

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()
